kind: pipeline
name: default

steps:
- name: build
  image: ruby
  commands:
      - gem install bundler
      - bundle install
      - bundle exec jekyll build 
- name: deploy
  image: cschlosser/drone-ftps
  settings:
    hostname: 57562.w62.wedos.net:21
    secrets: [ ftp_username, ftp_password ]
    secure: true
    dest_dir: /www/
    src_dir: /_site/
