language: ruby
rvm:
  - 2.4.1

script:
  - bundle exec jekyll build  


after_success:
  - cd ./_site && find . -type f -exec curl -u $FTP_USER:$FTP_PASS -k --ftp-ssl --ftp-create-dirs -T {} ftp://$FTP_HOST/www/subdom/jekyll/{} \;
