title:            SPINTOP.CZ
description:      Site about top spinning.

# put your disqus here
disqus_shortname:
reading_time:     false # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: //spintop.cz


# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Triky'
    url: '/triky/'
    submenu:
      - title: 'Tutoriály'
        url: '/tutorialy/'
      - title: 'Patche'
        url: '/patche/'
  - title: 'Soutěže'
    url: '/souteze/'
    submenu:
      - title: 'Kalendář akcí'
        url: '/kalendar-akci/'
      - title: 'Systémy soutěžení'
        url: '/systemy-soutezeni/'
      - title: 'Výsledky'
        url: '/vysledky/'
      - title: 'Photo contest'
        url: '/photo-contest/'  
  - title: 'Historie'
    url: '/historie/'
  - title: 'Odkazy'
    url: '/odkazy/'
  - title: 'ITSA'
    url: '/mezinarodni-spintop-asociace-itsa/'
  - title: 'Jak začít'
    url: '/jak-zacit/'

# Owner/author information
owner:
  name:           Jakub Konečný
  site:           http://spintop.cz
  avatar:         images/avatar.jpg
  bio:            "S bráchou Danem už se docela dlouho věnujeme freestylovému káčování a chtěli bychom ho prostřednictvím webu přiblížit i ostatním."
  email:          info@spintop.cz
  # Twitter nick for use in Twitter cards and follow button.
  # twitter: aron_bordin # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  # github: aron-bordin

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
#twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
#  - title: "github"
#    url: "https://github.com/aron-bordin"
#  - title: "linkedin"
#    url: "https://br.linkedin.com/in/aronbordin"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UCIwuVwZS1M54a4xwBsUCwDw"

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-48587462-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#timezone:    America/New_York
#locale:      en_US
locale:      cs_CZ
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 10

# if true, shows the floatting share buttons
float_share: false

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
plugins: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
